version: "3"
services:
  sort-db:
    image: postgres:9.4.5
    network_mode: bridge
    container_name: sort-db
    volumes:
      - sort-db-data:/var/lib/postgresql/data
    expose:
      - 5432
        #    ports:
        #      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
    restart: unless-stopped
# APP*****************************************
  sort-rest:
    build: .
    network_mode: bridge
    container_name: sort-rest
    expose:
      - 8081
    ports:
      - 8081:8080
    restart: unless-stopped
    depends_on:
      - sort-db
    links:
      - sort-db
    
volumes:
    sort-db-data:
